###############################################################################
#                        Quickstart Imagestreams Template                     #
###############################################################################
apiVersion: template.openshift.io/v1
kind: Template
message: Deploy Quickstart complete
metadata:
  labels:
    template: build-quickstart-images
  name: build-quickstart-images
  annotations:
    description: Deploy Quickstart
    openshift.io/display-name: Deploy Quickstart
    openshift.io/long-description: Deploy Quickstart
    openshift.io/provider-display-name: ServiceNow
    openshift.io/support-url: https://github.com/advlab/triton
    tags: servicenow
objects:
###############################################################################
#                             Tomcat Image Stream                            #
###############################################################################
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    labels:
      app: quickstart
    name: tomcat
  spec:
    lookupPolicy:
      local: false
    tags:
      - from:
          kind: DockerImage
          name: 'tomcat:jdk8-openjdk'
        importPolicy: {}
        name: jdk8-openjdk
        referencePolicy:
          type: Source    
###############################################################################
#                             Jenkins Image Stream                            #
###############################################################################
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    labels:
      app: quickstart
    name: jenkins
  spec:
    lookupPolicy:
      local: false
    tags:
      - from:
          kind: DockerImage
          name: 'jenkins/jenkins:lts-centos'
        importPolicy: {}
        name: lts-centos
        referencePolicy:
          type: Source    