###############################################################################
#                        Quickstart Image Builder Template                    #
###############################################################################
apiVersion: v1
kind: Template
message: Quickstart Image Builder is complete
metadata:
  labels:
    template: build-quickstart-images
  name: build-quickstart-images
  annotations:
    description: Quickstart Image Builder Template
    iconClass: icon-jenkins
    openshift.io/display-name: Quickstart Image Builder Template
    openshift.io/long-description: Quickstart Image Builder Template
    openshift.io/provider-display-name: ServiceNow
    openshift.io/support-url: https://github.com/advlab/triton
    tags: servicenow
objects:
###############################################################################
#                              Build Tomcat Image                             #
###############################################################################
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      template.alpha.openshift.io/wait-for-ready: 'true'
    labels:
      template: build-tomcat-image
    name: build-tomcat-image
  spec:
    resources:
      requests:
        cpu: "1000m"
        memory: "4Gi"
      limits:
        cpu: "1000m"
        memory: "4Gi"
    output:
      to:
        kind: ImageStreamTag
        name: quickstart-tomcat:latest
    source:
      git:
        uri: ssh://git@github.com/advlab/triton.git
        ref: bravo
      sourceSecret:
        name: github-triton
      type: Git
    strategy:
      type: Docker
      dockerStrategy:
        dockerfilePath: tomcat/Dockerfile
    triggers:
    - type: Generic
      generic:
        secret: github-triton
        allowEnv: true
  status:
    lastVersion: 0
###############################################################################
#                               Build Jenkins Image                           #
###############################################################################
- apiVersion: v1  
  kind: BuildConfig
  metadata:
    annotations:
      template.alpha.openshift.io/wait-for-ready: 'true'
    labels:
      template: build-jenkins-image
    name: build-jenkins-image
  spec:
    resources:
      requests:
        cpu: "1000m"
        memory: "4Gi"
      limits:
        cpu: "1000m"
        memory: "4Gi"
    output:
      to:
        kind: ImageStreamTag
        name: quickstart-jenkins:latest
    source:
      git:
        uri: ssh://git@github.com/advlab/triton.git
        ref: bravo
      sourceSecret:
        name: github-triton
      type: Git
    strategy:
      type: Docker
      dockerStrategy:
        dockerfilePath: jenkins/Dockerfile
        env:
          - name: JENKINS_VERSION
            value: ${JENKINS_VERSION}                
    triggers:
    - type: Generic
      generic:
        secret: github-triton
        allowEnv: true
  status:
    lastVersion: 0    
################################################################################
#                            Template Parameters                               #
################################################################################
parameters:
- name: JENKINS_VERSION
  description: Jenkins Version
  displayName: Jenkins Version
  # value: 2.176.3 
  # value: 2.190.2
  value: 2.190.3
  required: true