###############################################################################
#                         Quickstart Deployment Template                      #
###############################################################################
apiVersion: template.openshift.io/v1
kind: Template
message: Deploy Quickstart complete
metadata:
  labels:
    template: deploy-quickstart
  name: deploy-quickstart
  annotations:
    description: Deploy Quickstart
    openshift.io/display-name: Deploy Quickstart
    openshift.io/long-description: Deploy Quickstart
    openshift.io/provider-display-name: ServiceNow
    openshift.io/support-url: https://github.com/advlab/triton
    tags: servicenow
objects:
################################################################################
#                       Tomcat Deployment Configuration                       #
################################################################################
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: ${CUSTOMER_ID}
    name: ${CUSTOMER_ID}-deploy-tomcat
  spec:
    replicas: 1
    selector:
      app: ${CUSTOMER_ID}
      deploymentconfig: ${CUSTOMER_ID}-deploy-tomcat
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        labels:
          app: ${CUSTOMER_ID}
          deploymentconfig: ${CUSTOMER_ID}-deploy-tomcat
      spec:
        containers:
          - env:
              - name: TOMCAT_USER
                value: ${TOMCAT_USER}
              - name: TOMCAT_PASSWORD
                value: ${TOMCAT_PASSWORD}                
            image: 'tomcat'
            imagePullPolicy: IfNotPresent
            name: ${CUSTOMER_ID}-tomcat
            ports:
              - containerPort: 8080
                protocol: TCP
            resources:
              limits:
                memory: ${TOMCAT_MEMORY_LIMIT}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        serviceAccountName: triton
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
      - type: ConfigChange
      - imageChangeParams:
          automatic: true
          containerNames:
            - ${CUSTOMER_ID}-tomcat
          from:
            kind: ImageStreamTag
            name: 'tomcat:jdk8-openjdk'
        type: ImageChange
################################################################################
#                                Tomcat Service                                #
################################################################################
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: ${CUSTOMER_ID}
    name: ${CUSTOMER_ID}-tomcat
  spec:
    ports:
      - name: 8080-tcp
        port: 8080
        protocol: TCP
        targetPort: 8080
    selector:
      deploymentconfig: ${CUSTOMER_ID}-deploy-tomcat
    sessionAffinity: None
    type: ClusterIP
  status:
  loadBalancer: {}
################################################################################
#                                Tomcat Route                                  #
################################################################################
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    labels:
      app: ${CUSTOMER_ID}
    name: ${CUSTOMER_ID}-tomcat
  spec:
    port:
      targetPort: 8080-tcp
    to:
      kind: Service
      name:  ${CUSTOMER_ID}-tomcat
      weight: 100
    wildcardPolicy: None
################################################################################
#                                  Jenkins PVC                                 #
################################################################################
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    labels:
      app: ${CUSTOMER_ID}
    name: ${CUSTOMER_ID}-jenkins-data
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: ${JENKINS_VOLUME_CAPACITY}    
################################################################################
#                       Jenkins Deployment Configuration                       #
################################################################################
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: ${CUSTOMER_ID}
    name: ${CUSTOMER_ID}-deploy-jenkins
  spec:
    replicas: 1
    selector:
      app: ${CUSTOMER_ID}
      deploymentconfig: ${CUSTOMER_ID}-deploy-jenkins
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      recreateParams:
        timeoutSeconds: 600
      type: Recreate
    template:
      metadata:
        labels:
          app: ${CUSTOMER_ID}
          deploymentconfig: ${CUSTOMER_ID}-deploy-jenkins
      spec:
        containers:
          - env:
              - name: JENKINS_USER
                value: ${JENKINS_USER}
              - name: JENKINS_PASSWORD
                value: ${JENKINS_PASSWORD}                            
              - name: GITHUB_ID
                value: ${GITHUB_ID}
              - name: TOMCAT_USER
                value: ${TOMCAT_USER}
              - name: TOMCAT_PASSWORD
                value: ${TOMCAT_PASSWORD}
              - name: CUSTOMER_ID
                value: ${CUSTOMER_ID}                
            image: 'jenkins'
            imagePullPolicy: IfNotPresent
            name: ${CUSTOMER_ID}-jenkins
            ports:    
              - containerPort: 8080
                protocol: TCP
              - containerPort: 50000
                protocol: TCP
            resources:
              limits:
                memory: ${JENKINS_MEMORY_LIMIT}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            volumeMounts:
              - mountPath: /var/jenkins_home
                name: ${CUSTOMER_ID}-jenkins-data
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        serviceAccountName: triton
        terminationGracePeriodSeconds: 30
        volumes:
          - name: ${CUSTOMER_ID}-jenkins-data
            persistentVolumeClaim:
              claimName: ${CUSTOMER_ID}-jenkins-data
    test: false
    triggers:
      - type: ConfigChange
      - imageChangeParams:
          automatic: true
          containerNames:
            - ${CUSTOMER_ID}-jenkins
          from:
            kind: ImageStreamTag
            name: 'jenkins:lts-centos'
        type: ImageChange
################################################################################
#                               Jenkins Service                                #
################################################################################
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: ${CUSTOMER_ID}
    name: ${CUSTOMER_ID}-jenkins
  spec:
    ports:
      - name: 8080-tcp
        port: 8080
        protocol: TCP
        targetPort: 8080
      - name: 50000-tcp
        port: 50000
        protocol: TCP
        targetPort: 50000
    selector:
      deploymentconfig: ${CUSTOMER_ID}-deploy-jenkins
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}        
################################################################################
#                                Jenkins Route                                 #
################################################################################
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    labels:
      app: ${CUSTOMER_ID}
    name: ${CUSTOMER_ID}-jenkins
  spec:
    port:
      targetPort: 8080-tcp
    to:
      kind: Service
      name: ${CUSTOMER_ID}-jenkins
      weight: 100
    wildcardPolicy: None     
################################################################################
#                            Template Parameters                               #
################################################################################
parameters:
- name: CUSTOMER_ID
  description: Customer ID (e.g. acme)
  displayName: Customer ID
  required: true
- name: GITHUB_ID
  description: GitHub ID (e.g. dsmith)
  displayName: GitHub ID
  required: true
  value: devopsmaniac  
- name: TOMCAT_USER
  description: Tomcat User (e.g. admin)
  displayName: Tomcat User
  required: true
  value: admin
- name: TOMCAT_PASSWORD
  description: Tomcat Password (e.g. changeit)
  displayName: Tomcat Password
  required: true
  value: changeit
- name: JENKINS_USER
  description: Jenkins User (e.g. admin)
  displayName: Jenkins User
  required: true
  value: admin
- name: JENKINS_PASSWORD
  description: Tomcat Password (e.g. changeit)
  displayName: Tomcat Password
  required: true
  value: changeit
- name: TOMCAT_MEMORY_LIMIT
  description: Maximum amount of memory the Tomcat container can use.
  displayName: Tomcat Memory Limit
  required: true
  value: 1Gi  
- name: JENKINS_MEMORY_LIMIT
  description: Maximum amount of memory the Jenkins container can use.
  displayName: Jenkins Memory Limit
  required: true
  value: 1Gi
- name: JENKINS_VOLUME_CAPACITY
  description: Volume space available for Jenkins data, e.g. 512Mi, 2Gi.
  displayName: Jenkins Volume Capacity
  required: true
  value: 5Gi